# Generated by Django 5.0.6 on 2024-07-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_agency_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='branch_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
