# Generated by Django 5.0.6 on 2024-07-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_branches_branch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='employee_credential',
        ),
    ]
